; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 11220624-x86_64 MS Windows              
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppInfer                                  = true                                    
ppNJ                                     = true                                    
[ AnalysisSettings ]
Analysis                                 = Phylogeny Reconstruction                
Scope                                    = All Selected Taxa                       
Statistical Method                       = Neighbor-joining                        
Phylogeny Test                           = ====================                    
Test of Phylogeny                        = Bootstrap method                        
No. of Bootstrap Replications            = 10000                                   
Substitution Model                       = ====================                    
Substitutions Type                       = Nucleotide                              
Model/Method                             = Kimura 2-parameter model                
Fixed Transition/Transversion Ratio      = Not Applicable                          
Substitutions to Include                 = d: Transitions + Transversions          
Rates and Patterns                       = ====================                    
Rates among Sites                        = Uniform Rates                           
Gamma Parameter                          = Not Applicable                          
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Pairwise deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
System Resource Usage                    = ====================                    
Number of Threads                        = 20                                      
Genetic Code Table                       = Not Applicable                          
Genetic Code                             = Not Applicable                          
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
